name: CI-CD-Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Validate Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Validate index.html
        run: |
          if [ ! -f index.html ]; then
            echo "index.html missing!"
            exit 1
          fi
          echo "✅ HTML validation passed"

  cd:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy EC2 + S3 via Terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Show Deployment Info
        run: |
          echo "🚀 Deployment completed!"
          echo "EC2 Public IP: $(terraform output -raw ec2_public_ip)"
          echo "S3 Bucket: $(terraform output -raw s3_bucket)"